start:
	npx babel-node src/bin/.js  /src/before.json /src/after.json
install:
	npm ci
build:
	rm -rf dist
	npm run build
lint:
	npx eslint .
test:
	npm test
test-coverage:
	npm test -- --coverage

.PHONY: test
